services:
  backend:
    build:
      context: ./Server
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: Paisanabuils
      DATABASE_PASSWORD: P123
      DATABASE_NAME: DatabaseEco

  frontend:
    build:
      context: ./Web
    ports:
      - "80:80"

  db:
    image: postgis/postgis
    platform: linux/amd64
    environment:
      POSTGRES_USER: Paisanabuils
      POSTGRES_PASSWORD: P123
      POSTGRES_DB: DatabaseEco
    ports:
      - "5432:5432"
    volumes:
      - my_db_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
volumes:
  my_db_data:
