# Escolha a imagem base
FROM node:18

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /usr/src/app

# Copie o package.json e o package-lock.json (se disponível)
COPY package*.json ./

# Instale as dependências do projeto
RUN npm install

# Copie os arquivos do projeto para o diretório de trabalho
COPY . .

# Exponha a porta que o servidor Node.js utiliza
EXPOSE 4000

# Comando para rodar a aplicação
CMD ["npm", "start"]
