# Fase de construção
FROM node:18 AS build
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Fase de execução
FROM nginx:alpine
# Copia os arquivos estáticos do build React para o diretório do servidor Nginx
COPY --from=build /usr/src/app/build /usr/share/nginx/html
# Expõe a porta 80 para acesso HTTP
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
